---
name: CI
on: 
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: matrix.os
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - head
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: rake test
        run: |
          rake test
        timeout-minutes: 3
