---
name: CI
on: 
  push:
    branches: 
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: >-
      test ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - head
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: load ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: rake test
        run: |
          bundle exec rake test
        timeout-minutes: 3
